# We fix the version of the requirements to avoid incompatibilities
# jupyterlab version is the same than in binder
name: introduction_gwosc_data
channels:
  - conda-forge
dependencies:
  - jupyterlab=4.2.5
  - h5py
  - matplotlib
  - scipy
  - gwpy
  - codespell=2.3.0
